### PR TITLE
Spec with defaults

### LINKED ISSUE #84: Fix regression introduced in #83
In #83 we added a temporary workaround for spec-vs-actual comparison. Now integration tests are failing. Obviously this need to be fixed asap.
Perhaps should address the issue properly. The only fix that comes to mind is applying defaults locally to the spec and then comparing with the "actual" object.

### PR DESCRIPTION
**Pull request by ash2k**
Fixes #84. There is more work to do to make it handle special fields properly.

### CODE REVIEW

File: pkg/app/app.go [hunk 1]
```diff
@@ -114,7 +114,7 @@ func (a *App) Run(ctx context.Context) error {
 	}
 
 	queue := workqueue.NewNamedRateLimitingQueue(workqueue.DefaultControllerRateLimiter(), "bundle")
-	cntrlr := controller.New(bundleInf, tprInf, bundleClient, bs, sc, rc, scheme.DeepCopy, rawStore, queue, a.Workers, a.ResyncPeriod, resourceInfs)
+	cntrlr := controller.New(bundleInf, tprInf, bundleClient, bs, sc, rc, scheme, rawStore, queue, a.Workers, a.ResyncPeriod, resourceInfs)
```
Comment (nilebox) [inline pkg/app/app.go]: too many arguments for a method :/

File: types.go [hunk 2]
```diff
@@ -176,6 +176,12 @@ func (bs *BundleStatus) ShortString() string {
 			buf.WriteString(cond.Reason)
 			buf.WriteByte('"')
 		}
+		if cond.Message != "" {
+			buf.WriteByte(' ')
```
Comment (nilebox) [inline types.go]: Isn't it better to write the result of `fmt.Sprintf()`? It would make it more readable
